FinalProject/FinalProject/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as vr
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('MovieRate/', include('MovieRate.urls')),
    path('admin/', admin.site.urls),
    path('register/', vr.register, name="register"),
    path('', include("django.contrib.auth.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FinalProject/MovieRate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_id>", views.movie_view, name="movie_view"),
    path('rate_movie/', views.rate_movie, name='rate_movie'),
    path('browse/', views.browse_movies, name="browse_movies"),
    path('movies_by_genre/<int:genre_id>/', views.movies_by_genre, name="movies_by_genre"),
    path('profile/', views.profile, name='profile'),
    path('search/', views.search_movies, name="search_movies")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FinalProject/MovieRate/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
# Create your models here.

#genre table model
class Genre(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

#movie table model
class Movie(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    genre = models.ManyToManyField(Genre)
    release_date = models.DateField()
    director = models.CharField(max_length=255)
    cover_image = models.ImageField(upload_to='covers/', null=True, blank=True)

    def __str__(self):
        return self.title

#movie rating table model
class MovieRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) #if the user who submitted is deleted, the whole rating should be deleted
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE) #if the movie is deleted, the whole rating should be deleted
    rating = models.DecimalField(default=0, max_digits=2, decimal_places=1, validators=[MaxValueValidator(5)])

    def __str__(self):
        return f"{self.user.username} - {self.movie.title}: {self.rating}"

#average rating table model
class AverageRating(models.Model):
    movie = models.OneToOneField(Movie, on_delete=models.CASCADE)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=50, default="")
    bio = models.TextField(blank=True)

# Signal function to create AverageRating for new Movie objects
@receiver(post_save, sender=Movie)
def create_average_rating(sender, instance, created, **kwargs):
    if created:
        AverageRating.objects.create(movie=instance)

# Define the signal for updating the average rating
@receiver(post_save, sender=MovieRating)
@receiver(post_delete, sender=MovieRating)
def update_average_rating(sender, instance, **kwargs):
    movie = instance.movie
    user_ratings = MovieRating.objects.filter(movie=movie)
    total_ratings = sum(rating.rating for rating in user_ratings)
    num_ratings = user_ratings.count()
    average_rating = total_ratings / num_ratings if num_ratings else 0

    # Update the AverageRating model
    avg_rating, created = AverageRating.objects.get_or_create(movie=movie)
    avg_rating.average_rating = average_rating
    avg_rating.save()

FinalProject/MovieRate/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['display_name', 'bio']


class RatingForm(forms.Form):
    rating = forms.DecimalField(min_value=1, max_value=5, decimal_places=1, required=True)

FinalProject/MovieRate/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import *
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from .forms import UserProfileForm, RatingForm

# Create your views here.


def index(request):
    user = request.user
    top_rated_movies = Movie.objects.order_by('-averagerating__average_rating')[:5]  # Get the top 5 movies ordered by rating

    if user.is_authenticated:
        # For authenticated users, check if they have rated any movies with 4 stars or above
        user_rated_movies = MovieRating.objects.filter(user=user, rating__gte=4)
        if user_rated_movies.exists():
            # If the user has rated movies, get the genres of the movies they have rated highly
            # Get the ids of the genres of the movies the user has rated 
            top_genre_ids = user_rated_movies.values_list('movie__genre__id', flat=True)
            # Get the recommended movies that match the user's top genres
            recommended_movies = Movie.objects.filter(genre__id__in=top_genre_ids).distinct()[:5]
            if len(recommended_movies) < 5:
                # If there are not enough movies based on the user's preferences, include default recommendations
                # Merge default recommendations with user-based recommendations
                recommended_movies |= top_rated_movies
        else:
            # If the user has not rated any movies, provide fallback standard recommendations
            recommended_movies = top_rated_movies
    else:
        # Non-registered users get standard recommendations, which are not currently visible
        recommended_movies = top_rated_movies

    return render(request, 'MovieRate/index.html', {'user': user, 'recommended_movies': recommended_movies})


def movie_view(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    average_rating = AverageRating.objects.filter(movie=movie).first()
    user_rating = None

    if request.user.is_authenticated:
        user_rating = MovieRating.objects.filter(user=request.user, movie=movie).first()

    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid() and request.user.is_authenticated:
            rating = form.cleaned_data['rating']
            user_rating, created = MovieRating.objects.get_or_create(user=request.user, movie=movie)
            user_rating.rating = rating
            user_rating.save()
            return redirect('movie_view', movie_id=movie.id)
    else:
        form = RatingForm()

    numratings = MovieRating.objects.filter(movie=movie).count()

    return render(request, 'MovieRate/movie_view.html', {
        'movie': movie,
        'average_rating': average_rating,
        'user_rating': user_rating,
        'rating_form': form,
        'numratings': numratings
    })

def rate_movie(request):
    if request.method == 'GET':
        movie_id = request.GET.get('movie_id')
        rating = request.GET.get('rating')
        user = request.user

        if user.is_authenticated:
            movie = get_object_or_404(Movie, pk=movie_id)
            user_rating, created = MovieRating.objects.get_or_create(user=user, movie=movie)
            user_rating.rating = rating
            user_rating.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error', 'message': 'User not authenticated.'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})


def browse_movies(request):
    genres = Genre.objects.filter(parent=None)
    return render(request, 'MovieRate/browse_movies.html', {'genres': genres})

def movies_by_genre(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    # Get the Q object to filter movies of the selected genre and its subgenres
    genre_and_subgenres = Q(genre=genre) | Q(genre__parent=genre)
    movies = Movie.objects.filter(genre_and_subgenres).distinct()
    return render(request, 'MovieRate/movies_by_genre.html', {'genre': genre, 'movies': movies})


def search_movies(request):
    query = request.GET.get('q')
    movies = []

    if query:
        if request.user.is_authenticated:
            filter_option = request.GET.get('filter')
            if filter_option == 'title':
                movies = Movie.objects.filter(title__icontains=query)
            elif filter_option == 'genre':
                movies = Movie.objects.filter(genre__name__icontains=query)
            else:
                movies = Movie.objects.filter(title__icontains=query) | Movie.objects.filter(genre__name__icontains=query)
        else:
            movies = Movie.objects.filter(title__icontains=query) | Movie.objects.filter(genre__name__icontains=query)

    movies = movies.distinct()

    return render(request, 'MovieRate/search_results.html', {'movies': movies, 'query': query})

@login_required
def profile(request):
    user = request.user
    try:
        profile = UserProfile.objects.get(user=user)
    except UserProfile.DoesNotExist:
        # If UserProfile doesn't exist, create it with default display name and bio
        profile = UserProfile.objects.create(user=user, display_name=user.username)

    ratings = MovieRating.objects.filter(user=user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = UserProfileForm(instance=profile)

    return render(request, 'MovieRate/profile.html', {'profile': profile, 'ratings': ratings, 'form': form})

FinalProject/MovieRate/templates/MovieRate/browse_movies.html
<!-- browse_movies.html -->

{% extends "MovieRate/layout.html" %}



{% block content %}
  <h2>Browse Movies by Genre</h2>
  <div class="row">
    {% for genre in genres %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'movies_by_genre' genre.id %}">{{ genre.name }}</a></h5>
            <p class="card-text">
              {% if genre.genre_set.all %}
                Subgenres:
                {% for subgenre in genre.genre_set.all %}
                  <a href="{% url 'movies_by_genre' subgenre.id %}">{{ subgenre.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

FinalProject/MovieRate/templates/MovieRate/index.html
{% extends "MovieRate/layout.html" %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
    <!-- Content for logged-in users -->
    <h2>Welcome, {{ user.username }}!</h2>
{% if recommended_movies %}
      <h3>Recommended for You:</h3>
      <div class="movie-grid">
        {% for movie in recommended_movies %}
          <div class="movie-item">
            {% if movie.cover_image %}
			<a href="{% url 'movie_view' movie.id %}">
              <img src="{{ movie.cover_image.url }}" alt="{{ movie.title }} Cover" width="150">
			</a>
            {% else %}
			<a href="{% url 'movie_view' movie.id %}">
              <img src="{% static 'default_image.png' %}" alt="Default Cover Image" width="150">
			</a>
            {% endif %}
            <br>
            <a href="{% url 'movie_view' movie.id %}">
              <strong>{{ movie.title }}</strong> 
            </a>
            <br>
            {% if movie.averagerating.average_rating > 0 %}
		<p>Average Rating: {{ movie.averagerating.average_rating }} ★ </p>
		{% else %}
		<p>No reviews</p>
		{% endif %}
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>No recommendations at the moment. Please rate some movies to get personalized recommendations!</p>
    {% endif %}
  {% else %}
    <!-- Content for non-logged-in users -->
    <h2>Welcome to MovieRate!</h2>
    <p>Please <a href="{% url 'login' %}">Login</a> or <a href="{% url 'register' %}">Register</a> to access the following features:</p>
	<ul> <li> Submit your movie ratings </li>
	<li> Your own profile page </li>
	<li> Search filters </li>
	<li> A recommendation list tailored to your preferences </li>
	</ul>
  {% endif %}
{% endblock %}

FinalProject/MovieRate/templates/MovieRate/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>MovieRate: All Your Favorite Movies in One Place!</title>
  <link rel="icon" href="{% static 'logo.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Pangolin&display=swap">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img class="logo-img" src="{% static 'logo.png' %}" alt="Logo">
        <span class="brand-text"> <b>MovieRate</b></span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        ︾
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'search_movies' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            {% if user.is_authenticated %}
            <select class="form-control mr-sm-2" name="filter">
              <option value="all">All</option>
              <option value="title">Title</option>
              <option value="genre">Genre</option>
            </select>
            {% else %}
            <input type="hidden" name="filter" value="all" id="search-filter">
            {% endif %}
            <button class="btn custom-search-btn my-2" type="submit">🔍</button>
          </form>
          <div class="navbar-links">
            {% if user.is_authenticated %}
            <a href="{% url 'browse_movies' %}">Browse</a>
            <a href="{% url 'profile' %}">My Profile</a>
            <a href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'browse_movies' %}">Browse</a>
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
            {% endif %}
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

  <div class="content">
  <main class="container">
    {% block content %}
    <!-- Content for each page goes here -->
    {% endblock %}
  </main>
  </div>

  <footer class="footer mt-auto py-3">
    <div class="container">
      <p>&copy; {% now "Y" %} MovieRate. All rights reserved.</p>
    </div>
  </footer>

  <!-- JavaScript and other script tags go here -->
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

FinalProject/MovieRate/templates/MovieRate/movie_view.html
<!-- movie_view.html -->

{% extends "MovieRate/layout.html" %}
{% load static %}


{% block content %}
  <h3><center><strong>{{ movie.title }}</center></strong></h3>
    {% if movie.cover_image %}
    <img class="cover-img" src="{{ movie.cover_image.url }}" alt="{{ movie.title }} Cover Image" style="max-width: 300px;">
  {% else %}
	<img class="cover-img" src="{% static 'default_image.png' %}" alt="Default Cover Image" width="150">
    <center><p>No cover image available.</p></center>
  {% endif %}
  <br>
  
  <center><p>{{ movie.description }}</p>
      <p>Genres:
        {% for genre in movie.genre.all %}
          <a href="{% url 'movies_by_genre' genre.id %}">{{ genre.name }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </p>
	  
	<p><strong>Director:</strong> {{ movie.director }}</p>
	<p><strong>Release Date:</strong> {{ movie.release_date }}</p>

	
	{% if movie.averagerating.average_rating > 0 %}
    <p><strong>Average Rating:</strong> {{ movie.averagerating.average_rating }} ★ ({{ numratings }})</p>
	{% else %}
    <p>This movie has not been reviewed yet ☹</p>
	{% endif %}

<!-- Movie rating section -->
{% if user.is_authenticated %}
<div>
  {% if user_rating %}
    <p>Your Rating: {{ user_rating.rating }} ★</p>
  {% else %}
    <p>Rate this movie:</p>
    <input type="number" id="rating-input" min="1" max="5" step="0.5">
    <button class="btn custom-search-btn my-2" id="submit-rating">Submit</button>
  {% endif %}
</div>
<br>
{% else %}
<p> To submit a rating of this movie, please <a href="{% url 'login' %}">Login</a> or <a href="{% url 'register' %}">Register</a> </p>
{% endif %} </center>


<!-- JavaScript code for user rating -->
<script>
  $(document).ready(function () {
    // Get the rating input field and submit button
    var ratingInput = $('#rating-input');
    var submitButton = $('#submit-rating');

    // Check if the user has already rated the movie
    var userRating = {{ user_rating|default_if_none:"null" }};

    if (userRating !== null) {
      // User has already rated the movie, display their rating
      ratingInput.hide();
      submitButton.hide();

      // Show the user's rating
      $('#user-rating').text('Your Rating: ' + userRating);
    } else {
      // User has not rated the movie, show the input field and submit button
      $('#user-rating').hide();

      // Handle the click event on the submit button
      submitButton.click(function () {
        // Get the rating value from the input field
        var rating = ratingInput.val();

        // Make a GET request to the rate_movie view with the movie_id and rating as parameters
        $.ajax({
          type: 'GET',
          url: 'rate_movie',
          data: {
            movie_id: {{ movie.id }},
            rating: rating
          },
          success: function (data) {
            // Check if the rating was successful
            if (data.status === 'success') {
              location.reload();
            } else {
              // Display an error message
              alert('Error rating the movie.');
            }
          },
          error: function () {
            // Display an error message
            alert('Error rating the movie.');
          }
        });
      });
    }
  });
</script>
{% endblock %}

FinalProject/MovieRate/templates/MovieRate/movies_by_genre.html
<!-- movies_by_genre.html -->

{% extends "MovieRate/layout.html" %}
{% load static %}
{% block content %}
  <h2>{{ genre.name }} Movies</h2>

  <div class="movie-grid">
    {% for movie in movies %}
      <div class="movie-item">
        {% if movie.cover_image %}
		<a href="{% url 'movie_view' movie.id %}">
          <img src="{{ movie.cover_image.url }}" alt="{{ movie.title }} Cover" width="150">
		</a>
        {% else %}
		<a href="{% url 'movie_view' movie.id %}">
          <img src="{% static 'default_image.png' %}" alt="Default Cover Image" width="150">
		</a>
        {% endif %}
        <br>
        <a href="{% url 'movie_view' movie.id %}">
          <strong>{{ movie.title }}</strong>
        </a>
        {% if movie.averagerating.average_rating > 0 %}
		<p>{{ movie.averagerating.average_rating }} ★ </p>
		{% else %}
		<p>No reviews</p>
		{% endif %}
        <p>Release Date: {{ movie.release_date }}</p>
        <p>Director: {{ movie.director }}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

FinalProject/MovieRate/templates/MovieRate/profile.html
<!-- profile.html -->

{% extends "MovieRate/layout.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
  <h2>Welcome to Your Profile, {{ profile.display_name }}!</h2>
  <br>
  <p>Username: {{ profile.user }}</p>
  <p>Bio: {% if profile.bio %}{{ profile.bio }}{% else %}No bio available{% endif %}</p>

  <h3>Your Ratings</h3>
  <div class="movie-grid">
    {% for rating in ratings %}
      <div class="movie-item">
        {% if rating.movie.cover_image %}
			<a href="{% url 'movie_view' rating.movie.id %}">
          <img src="{{ rating.movie.cover_image.url }}" alt="{{ rating.movie.title }} Cover">
		  </a>
        {% else %}
			<a href="{% url 'movie_view' rating.movie.id %}">
          <img src="{% static 'default_image.png' %}" alt="Default Cover Image">
		  </a>
        {% endif %}
        <br>
        <a href="{% url 'movie_view' rating.movie.id %}">
          <strong>{{ rating.movie.title }}</strong>
        </a>
        <br>
        Your Rating: {{ rating.rating }} ★
      </div>
    {% endfor %}
  </div>
  
  
  <button class="btn custom-search-btn my-5" id="edit-profile-btn" class="edit-profile-button my-5">Edit Profile</button>

  <div id="edit-profile-form" style="display: none;">
    <h3>Edit Profile</h3>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}  <!-- Render the form using crispy_forms_tags -->
      <input type="submit" value="Save">
    </form>
  </div>
  <br>


  

  <script>
    const editProfileBtn = document.getElementById('edit-profile-btn');
    const editProfileFormContainer = document.getElementById('edit-profile-form');

    editProfileBtn.addEventListener('click', function() {
      if (editProfileFormContainer.style.display === 'none') {
        editProfileFormContainer.style.display = 'block';
      } else {
        editProfileFormContainer.style.display = 'none';
      }
    });
  </script>
{% endblock %}

FinalProject/MovieRate/templates/MovieRate/search_results.html
{% extends "MovieRate/layout.html" %}
{% load static %}
{% block content %}
  <h2>Search Results for "{{ query }}"</h2>
  {% if movies %}
  <div class="movie-grid">
    {% for movie in movies %}
      <div class="movie-item">
        {% if movie.cover_image %}
		<a href="{% url 'movie_view' movie.id %}">
          <img src="{{ movie.cover_image.url }}" alt="{{ movie.title }} Cover" width="150">
		  </a>
        {% else %}
		<a href="{% url 'movie_view' movie.id %}">
          <img src="{% static 'default_image.png' %}" alt="Default Cover Image" width="150">
		  </a>
        {% endif %}
        <br>
        <a href="{% url 'movie_view' movie.id %}">
          <strong>{{ movie.title }}</strong>
        </a>
        <br>
        <p>Release Date: {{ movie.release_date }}</p>
        <p>Director: {{ movie.director }}</p>
      </div>
    {% endfor %}
  </div>
  {% else %}
    <p>No results found.</p>
  {% endif %}
{% endblock %}